---

- name: PHP SCL | install php packages
  yum:
    name: "{{ item }}"
    state: installed
  with_items: php_scl_php_packages
  when: php_scl_install_php
  tags:
    - scl
    - php
    - yum

- name: PHP SCL | set php to be available globally
  lineinfile:
    dest: "{{ php_scl_profile_d_directory }}/php.sh"
    state: present
    line: "source /opt/rh/*php*/enable"
    create: yes
    owner: root
    group: root
    mode: 0755
  when: php_scl_enable_globally
  tags:
    - scl
    - php
