---

- name: PHP 5.5 SCL | ensure scl-utils are installed
  yum:
    name: "{{ item }}"
    state: installed
  with_items: php55_scl_scl_utils_packages
  when: php55_scl_install_scl_repo
  tags:
    - scl
    - php
    - php55
    - yum

- name: PHP 5.5 SCL | install php 5.5 scl repository
  yum:
    name: "{{ php55_scl_scl_repo_url }}"
    state: installed
  when: php55_scl_install_scl_repo
  tags:
    - scl
    - php
    - php55
    - yum
