---

- name: PHP SCL | ensure scl-utils are installed
  yum:
    name: "{{ item }}"
    state: installed
  with_items: php_scl_scl_utils_packages
  when: php_scl_install_scl_repo
  tags:
    - scl
    - php
    - yum

- name: PHP SCL | install php scl repository
  yum:
    name: "{{ php_scl_scl_repo_url }}"
    state: installed
  when: php_scl_install_scl_repo
  tags:
    - scl
    - php
    - yum
